# %% [markdown]
# # Preprocess nvidia/OpenMathReasoning for Qwen3.5 2B Fine-tuning
# Converts the dataset to ChatML format for SFT training.

# %% Cell 1: Imports & Setup
import os
import json
import random
from datasets import load_dataset
from tqdm import tqdm

# Create output directory
os.makedirs("data", exist_ok=True)

print("Setup complete.")

# %% Cell 2: Helper Functions

def to_chatml(system: str, user: str, assistant: str) -> str:
    """Convert to ChatML format for Qwen3.5"""
    text = f"<|im_start|>system\n{system}<|im_end|>\n"
    text += f"<|im_start|>user\n{user}<|im_end|>\n"
    text += f"<|im_start|>assistant\n{assistant}<|im_end|>"
    return text

def save_jsonl(data: list, filename: str):
    """Save list of dicts to JSONL file"""
    filepath = os.path.join("data", filename)
    with open(filepath, "w", encoding="utf-8") as f:
        for item in data:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")
    print(f"Saved {len(data):,} samples to {filepath}")
    return len(data)

MATH_SYSTEM_PROMPT = """You are an expert mathematician. Solve problems step-by-step with clear reasoning. Show your complete thought process before giving the final answer."""

print("Helper functions defined.")

# %% Cell 3: Load Dataset (CoT split - Chain of Thought)
# The CoT split has 3.2M samples with detailed reasoning

print("Loading nvidia/OpenMathReasoning (cot split)...")
print("This is a large dataset (3.2M rows). Loading may take several minutes...")

ds = load_dataset("nvidia/OpenMathReasoning", split="cot")
print(f"Loaded {len(ds):,} samples")

# Preview columns
print(f"\nColumns: {ds.column_names}")
print(f"\nSample preview:")
print(f"Problem: {ds[0]['problem'][:200]}...")
print(f"Solution length: {len(ds[0]['generated_solution'])} chars")

# %% Cell 4: Process Dataset

print("\nProcessing dataset to ChatML format...")

processed = []
skipped = 0

for row in tqdm(ds, desc="Processing OpenMathReasoning"):
    problem = row.get("problem", "")
    solution = row.get("generated_solution", "")

    # Skip empty entries
    if not problem or not solution:
        skipped += 1
        continue

    # Create ChatML formatted text
    text = to_chatml(
        system=MATH_SYSTEM_PROMPT,
        user=problem,
        assistant=solution
    )

    processed.append({"text": text})

print(f"\nProcessed: {len(processed):,} samples")
print(f"Skipped (empty): {skipped:,} samples")

# %% Cell 5: Save Full Dataset

count = save_jsonl(processed, "openmath_reasoning_full.jsonl")

# %% Cell 6: Create Smaller Subset (Optional - for testing/limited resources)
# Qwen3.5 2B can train on full dataset, but subset is useful for quick experiments

SUBSET_SIZE = 100_000  # 100k samples for quick experiments

print(f"\nCreating {SUBSET_SIZE:,} sample subset...")

random.seed(42)
subset_indices = random.sample(range(len(processed)), min(SUBSET_SIZE, len(processed)))
subset = [processed[i] for i in subset_indices]

save_jsonl(subset, "openmath_reasoning_100k.jsonl")

# %% Cell 7: (Optional) Load TIR split for Tool-Integrated Reasoning
# Uncomment if you also want tool-integrated reasoning data

"""
print("\nLoading TIR split (Tool-Integrated Reasoning)...")
ds_tir = load_dataset("nvidia/OpenMathReasoning", split="tir")
print(f"TIR split: {len(ds_tir):,} samples")

processed_tir = []
for row in tqdm(ds_tir, desc="Processing TIR"):
    problem = row.get("problem", "")
    solution = row.get("generated_solution", "")
    if problem and solution:
        text = to_chatml(
            system=MATH_SYSTEM_PROMPT,
            user=problem,
            assistant=solution
        )
        processed_tir.append({"text": text})

save_jsonl(processed_tir, "openmath_reasoning_tir.jsonl")
"""

# %% Cell 8: Summary

print("\n" + "="*50)
print("PREPROCESSING COMPLETE")
print("="*50)

print(f"""
Output files in ./data/:
  - openmath_reasoning_full.jsonl  ({len(processed):,} samples)
  - openmath_reasoning_100k.jsonl  ({len(subset):,} samples)

Dataset info:
  - Source: nvidia/OpenMathReasoning (CoT split)
  - Format: ChatML for Qwen3.5
  - Solutions: Generated by DeepSeek-R1 and QwQ-32B

To load for training:
```python
from datasets import load_dataset
dataset = load_dataset("json", data_files="data/openmath_reasoning_100k.jsonl", split="train")
```

For Qwen3.5 2B, recommended to start with 100k subset due to VRAM constraints.
Full 3.2M dataset for multi-GPU or longer training.
""")
